### PR TITLE
⬆️ felixfbecker/language-server to 5.3.6

### PR DESCRIPTION
**Pull request by vinkla**
⬆️ felixfbecker/language-server to 5.3.6

### CODE REVIEW

**Comment by damieng** [comment]
Thanks!

**Comment by vinkla** [comment]
Thanks for the invite! Do I've permission to release new versions of the package as well?

**Comment by damieng** [comment]
I think we'll still want to co-ordinate releases for the short term.  We have an atom slack for more immediate communication.

**Comment by vinkla** [comment]
Okay, do you've a link to the Slack team?

**Comment by damieng** [comment]
https://discuss.atom.io/t/join-us-on-slack/16638 should get you going

**Pull request merged**
