### PR TITLE
Updated felixfbecker/language-server package

### PR DESCRIPTION
**Pull request by vinkla**
Updated the `felixfbecker/language-server` package to 5.1 ✨ 

https://github.com/felixfbecker/php-language-server/releases/tag/v5.1.0

### CODE REVIEW

**Comment by damieng** [comment]
This should also remove code format from our README.md given the release notes?

**Comment by vinkla** [comment]
I've pushed an update!

**Comment by Arcanemagus** [comment]
Wow, this was apparently backed by `PHP_CodeSniffer`, but people haven't even requested support for it in [linter-phpcs](https://atom.io/packages/linter-phpcs). I wonder if that's an exposure issue on `phpcs`'s part, or just an indicator of how bad it works 😛.

**Comment by developer-lindner** [comment]
Would be nice to have this in the next release... :)

**Comment by vinkla** [comment]
@damieng I've updated the README.md file as well.

**Comment by vinkla** [comment]
This pull request could potentially fix: https://github.com/atom/ide-php/issues/72#issuecomment-344247730

**Comment by vinkla** [comment]
@damieng I've pushed an update which will fix: https://github.com/atom/ide-php/issues/47#issuecomment-344843356

**Comment by vinkla** [comment]
@damieng Thanks! I'm curious though, why did you re-release it as v0.6.10?

**Comment by damieng** [comment]
I didn't re-release it with 0.6.10.  It is yet to go out.   

0.6.10 was released 19 days ago via apm as usual.  I had just forgotten to put the release notes for that version here on github's releases page.

**Comment by vinkla** [comment]
> 0.6.10 was released 19 days ago via apm as usual. I had just forgotten to put the release notes for that version here on GitHub's releases page.

Oh, I see. When will you release the new version?

**Comment by damieng** [comment]
I'm working on it right now, I had to make changes for the latest atom language client release.

**Pull request merged**
