### PR TITLE
Exclude non-essential files

### PR DESCRIPTION
**Pull request by vinkla**
This is a follow up pull request to #54.

### CODE REVIEW

**Comment by vinkla** [comment]
Any update on this pull request?

**Comment by damieng** [comment]
This would only save a few KB and stop people being able to composer install themselves if they wanted to do so - e.g. to bump up to a newer/beta language server we're not currently shipping.

**Comment by vinkla** [comment]
Saving a few KB could become huge overtime. What about not excluding the composer.json file?

**Comment by damieng** [comment]
We have a LOT of Atom packages we publish - I don't think we'll do this unless we want to do it org-wide.

**Comment by vinkla** [comment]
Okay, I'll go ahead and close this.

**Pull request closed without merging**
