### PR TITLE
⬆️ felixfbecker/language-server

### LINKED ISSUE #84: Update felixfbecker/language-server up to v5.1.2
`felixfbecker/language-server` v5.1.2 was released a day ago:

https://github.com/felixfbecker/php-language-server/releases

It contains some great improvements over the 5.1.0 (the version that `ide-php` is installing now according to `composer.lock` file):

https://github.com/atom/ide-php/blob/58a02fcb8f6bfdb7e47b277bad47f7cc502c9530/composer.lock#L311

Thanks in advance!

### PR DESCRIPTION
**Pull request by vinkla**
This release adds [Signature Help](https://github.com/felixfbecker/php-language-server/issues/547) support and bug fixes.

@damieng should we add Signature Help to the README?

This closes #84 and potentially #67.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
> @damieng should we add Signature Help to the README?

It should be added to the feature list there I'd say 😉.

**Comment by damieng** [comment]
Also needs this added to the consumedServices in the package.json to enable signature help (this goes for all new capabilities although the actual name of the service and whether it goes in consumed or provided depends on the service. Easiest is to copy it from another ide-x package like I did here

```json
    "signature-help": {
      "versions": {
        "0.1.0": "consumeSignatureHelp"
      }
}
```

**Comment by damieng** [comment]
One more thing about bumping the language server.   Because we don't require composer installed on users machines we instead download a tar.gz of it.  Before we can publish a new version the following steps need to happen;

1. `npm run server-install` to clear the vendor folder and download all dependencies
2. `npm run server-package` to create a php-ls-x.y.z.tar.gz from the vendor folder
3. Rename php-ls-x.y.z.tar.gz to the right LS version, e.g. php-ls.5.2.0.tar.gz
4. Start creating an issue on ide-php and drag the newly created tar.gz to upload it
5. Grab the url the upload generates from the issue and now you can close/disregard the issue
6. Update https://github.com/atom/ide-php/blob/master/lib/main.js#L8 with the new URL and file size

If you feel confident in trying those it would be a great help - keeping up with the pace of the PHP Language Server releases would be easier with a bit of help as I'm spread a bit thin across the other ide-x packages and the shared atom-languageclient.

**Comment by vinkla** [comment]
Thanks for taking me through the installation process. I'm happy to help out and will try to do so more in the future! Let me know if there is anything else I need to fix in this pull request.

**Comment by damieng** [comment]
Great, that's almost good to go. Just need to update the file size in main.js.  My download for that tar.gz says it's 4,110,960 bytes.

**Comment by vinkla** [comment]
Oh, that is true. I've pushed an update!

**Comment by vinkla** [comment]
Whoops, must have missed it. I've pushed an update!

**Comment by damieng** [comment]
Thank-you @vinkla !!

**Comment by damieng** [comment]
Out at 0.7.4 !

**Pull request merged**
