### PR TITLE
Add option to change AutoComplete suggestions pritority

### PR DESCRIPTION
**Pull request by martinfojtik**
~~This change require https://github.com/atom/atom-languageclient/pull/188~~

This is partial fix for https://github.com/atom/ide-php/issues/95

### CODE REVIEW

**Comment by martinfojtik** [comment]
@damieng What should I override in `getSuggestions`? I think we cant change priority of all suggestion inside `getSuggestions`, in this function we can change only order of suggestions from LSP.

**Comment by damieng** [comment]
Sorry, I meant we could override provideAutocomplete

**Comment by martinfojtik** [comment]
ok, now I am overriding only `provideAutocomplete`

**Comment by damieng** [comment]
Thanks!

**Pull request merged**
